
#include "..\header\sprites.h"


unsigned int SPACE_avion[AVION_Y_LENGTH][AVION_X_LENGTH]=
{	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	, // ->>>>> y
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,RED	,BLUE	,BLUE	,
	BLUE	,BLUE	,RED	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,RED	,BLUE	,BLUE	,
	BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,
	BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,
	BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,
	BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,
	BLUE	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,BLUE	,
	BLUE	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE};



#define SQUARE_METEORE // permet un affichage accelerer si le sprite est carré (mono couleur)
//unsigned int sprite_meteore[METEORE_Y_LENGTH][METEORE_X_LENGTH]={RED};

const uint8_t sprite_meteore[METEORE_Y_LENGTH*METEORE_X_LENGTH] = 
{
    0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F, //blue,blue,blue,blue,blue,blue,blue,blue
    0x00,0xFF,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00, //blue,red,red,red,red,red,red,blue
    0x00,0xFF,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00, //blue,red,red,red,red,red,red,blue
    0x00,0xFF,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00, //blue,red,red,red,red,red,red,blue
    0x00,0xFF,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00, //blue,red,red,red,red,red,red,blue
    0x00,0xFF,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00, //blue,red,red,red,red,red,red,blue
    0x00,0xFF,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00, //blue,red,red,red,red,red,red,blue
    0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F,0x00,0xF0,0x0F, //blue,blue,blue,blue,blue,blue,blue,blue
};

uint8_t SPACE_MISSILE[MISSILE_Y_LENGTH*MISSILE_X_LENGTH]= //mode blit, 3*8
{	
	0x00    ,0xFF  , 0x00 , 0xF0, 0x00 , 0X0F,  //blue,red,red,blue.
        0xF0    ,0x0F  , 0x00 , 0xF0, 0x0F , 0X00,  //red,red,red,red
        0x00    ,0xFF  , 0x00 , 0xF0, 0x00 , 0X0F,  //blue,red,red,blue
        0x00    ,0xFF  , 0x00 , 0xF0, 0x00 , 0X0F,  //blue,red,red,blue
        0xF0    ,0x0F  , 0x00 , 0xF0, 0x0F , 0X00,  //red,red,red,red
        0x00    ,0xFF  , 0x00 , 0xF0, 0x00 , 0X0F,  //blue,red,red,blue
        0x00    ,0xFF  , 0x00 , 0xF0, 0x00 , 0X0F,  //blue,red,red,blue
        0x00    ,0xFF  , 0xF0 , 0xFF, 0x00 , 0X0F  //blue,yellow,yellow,blue
};

uint8_t SPACE_BALLE[BALLES_Y_LENGTH]=
{	
	0xFF    ,0x0F  , 0xF0 , 0xFF, 0x0F , 0XF0  //YELLOW,YELLOW,YELLOW,YELLOW,
};
