
#include "..\header\sprites.h"


unsigned int SPACE_avion[AVION_Y_LENGTH][AVION_X_LENGTH]=
{	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	, // ->>>>> y
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,RED	,BLUE	,BLUE	,
	BLUE	,BLUE	,RED	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,RED	,BLUE	,BLUE	,
	BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,
	BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,
	BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,
	BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,
	BLUE	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,BLUE	,
	BLUE	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,
	BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,YELLOW	,YELLOW	,YELLOW	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE	,BLUE};


#define SQUARE_METEORE // permet un affichage accelerer si le sprite est carré (mono couleur)
unsigned int sprite_meteore[METEORE_Y_LENGTH][METEORE_X_LENGTH]={RED};
